project:
  type: website
  output-dir: docs

website:
  title: "footprints"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - default
      - brand
    css: styles.css

editor: visual

